import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import {Toaster} from "sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Inspage",
  description: "Generated by create next app",
  publisher: "Inspoflex",
  authors: [{ name: "Kudeng", url: "https://github.com/RIZKI-KUDENG" }],
  keywords: [
    "linktree",
    "inspage",
    "link in bio",
    "lynk id",
    "sukabumi",
    "inspage",
  ],
  icons: {
    icon: "/icon.png",
    shortcut: "/icon.png",
    apple: "/icon.png",
  },
  openGraph: {
    title: "Inspage",
    description: "Gabungkan semua media sosial, karya, dan portofolio dalam satu halaman estetik. Bagikan dengan mudah & pantau performanya.",
    url: "https://inspage.vercel.app",
    siteName: "Inspage",
    images: [
      {
        url: "/logo.jpg",
        width: 600,
        height: 400,
      },
    ],
    locale: "id-ID",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        <Providers>{children}
          <Toaster position="bottom-right" richColors />
        </Providers>
      </body>
    </html>
  );
}
